name: flapod
description: A simple Flutter app to display NASA's Astronomy Picture of the Day (APOD) with an FAQ section that supports clickable URLs.

# The following line prevents the package from being accidentally published to pub.dev using `flutter pub publish`.
publish_to: 'none' 

# The current version of the app
version: 1.0.0+1

# The Dart SDK constraint
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  url_launcher: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/FAQ.txt
    - assets/key.txt
